/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=1;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=2;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=3;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=4;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=5;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=6;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=7;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=8;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=9;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=10;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=11;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=12;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=13;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=14;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=15;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=16;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=17;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=18;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=19;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=20;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=21;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=22;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=23;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=24;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=25;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=26;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=27;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=28;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=29;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=30;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=31;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=32;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=33;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=34;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=35;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=36;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=37;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=38;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=39;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=40;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=41;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=42;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=43;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=44;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=45;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=46;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=47;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=48;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=49;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=50;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \
/usr/local/MATLAB/R2015b/bin/matlab -nodesktop -nosplash -nojvm -r "resize_size=224;index_part=51;interp_frames=16;run ./TIM_stream_sh.m;quit;" & \

